image: ruby:2.7

cache:
  paths:
    - vendor/

before_script:
  - gem install bundler
  - bundle install --path vendor

pages:
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public